### ISSUE TITLE
Installing NPM package using tags that include slashes

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/actions#14]
![Screen Shot 2019-10-10 at 12 53 24 PM](https://user-images.githubusercontent.com/29791650/66589933-9f620d80-eb5d-11e9-903c-12e92ca8d0f3.png)

I wanted to double check that the install instructions that are generated on our pull requests are accurate. Installing using version number (as shown in the screenshot above) works fine. However, now that we've incorporated tags to the publishing process, I was trying to install packages using tags and came across an issue.

For the most part there are no problems using `npm install <package>@<tag>`, but installing packages with tags that have slashes results in this error:

![Screen Shot 2019-10-10 at 1 01 55 PM](https://user-images.githubusercontent.com/29791650/66590185-3333d980-eb5e-11e9-9ff2-ede8e1d35a8c.png)

What should we do about this? Is there a workaround for this issue?

**Comment by cowboyd** [comment]
It sounds like we need to escape slashes. Given a branch named `mk/something-what` we could convert it into the npm tag`mk__something-what`

We just have to make sure that on the cleanup step, we take `mk__something-what` and check for a git branch named `mk/something-what`

**Comment by minkimcello** [comment]
@cowboyd Got the prototype working. We have a `save` argument that allows people to specify which tags to persist. Should we expect them to input `mk_something` (npm tag) or `mk/something` (branch)?

**Comment by minkimcello** [comment]
@cowboyd Not sure if it helps but I made a diagram to visualize the dilemma.

![tag input 001](https://user-images.githubusercontent.com/29791650/66608520-be27ca80-eb84-11e9-8396-46fb07be0469.jpeg)

**Comment by cowboyd** [comment]
I believe the terminology that you're looking for is "encoding" and "decoding", and yes we'll have to do that. The trick is that your encode/decode function pair needs to be an isomorphism: `decode(encode(x)) = x` if you have as part of your encoding an escape character, then you also need to encode your escape character.Let's say that we encode `/` as `_-` It means that we have to encode `_` as `__`

**Comment by cowboyd** [comment]
So in the example:

```js
gitbranch2npmtag("mk/ab") //> mk_ab
gitbranch2npmtag("mk/a/b") //> mk_a_b
gitbranch2npmtag("mk/a_b") //> mk_a__b
gitbranch2npmtag("mk/a__b") //> mk_a____b
```

Long story short is that git branches with `_` in them make ugly npm tags, but that just means we should avoid them.

**Comment by minkimcello** [comment]
@cowboyd
Do we need `_` to turn into `__`? Since we're only dealing with the branch name, I was thinking we could just turn `/` into `_` and nothing else. So the "life cycle" of these branch tags would look something like this:

```
function encode(tag) {
  return "$(echo $tag | sed 's/\//\_/g')";
}
```
on PR: 
```
npm publish --tag $(encode(branch-name-of-head-ref))
```
on Delete: 
```
for tag in $all-npm-tags // $tag is already encoded
  if 
    [ $tag = latest ] ||
    [ encode($keep-argument-from-workflow) | grep -e $tag ] ||
    [ encode($branches-from-github) | grep -e $tag]
      then
        keep $tag
  else
    remove $tag from npm
done
```
Avoiding the need to decode and just encoding whenever we're dealing with npm tags seems like it would be the safest approach?

**Comment by cowboyd** [comment]
The case I'm trying to avoid is:

1. Let's say we have a git branch called `mk_foo`
2. We create an npm tag `mk_foo`
3. branch is deleted.
4. We download the tag `mk_foo` from npm, and want to find out what branch to delete
5. We look for a git branch `mk/foo` but it doesn't exist, so we don't delete it.

**Comment by cowboyd** [comment]
> Do we need _ to turn into __

Yes.

Stated another way: If I have two branches, `mk/foo` and `mk_foo`, they will resolve to the same npm tag, so when they are pushed to their respective PRs, they'll overwrite each other. By the same token, removing one branch will remove the shared tag.

Your strategy of only writing an encoding function will work though. It's just the encoding that needs to be unique. `mk/foo` and `mk_foo` _must_ encode to different tags.

**Comment by minkimcello** [comment]
>     1. Let's say we have a git branch called `mk_foo`
>     2. We create an npm tag `mk_foo`
>     3. branch is deleted.
>     4. We download the tag `mk_foo` from npm, and want to find out what branch to delete
>     5. We look for a git branch `mk/foo` but it doesn't exist, so we don't delete it

In step 4, we're using branches to see which tags to delete and not the other way around. 
In step 5, we *delete* the tags of branches we can't find. So if we were to decode `mk_foo` tag to `mk/foo` and can't find it, `mk_foo` npm tag would be deleted (which would be the results we want but not with the correct method). But because we're not decoding in this case, we'd be looking for branch `mk_foo` which also won't exist so it would be removed for the right reasons... right?

> Stated another way: If I have two branches, mk/foo and mk_foo, they will resolve to the same npm tag, so when they are pushed to their respective PRs, they'll overwrite each other.

I was just thinking this too. I'll have the actions replace `_` with `__`. We don't have to worry about someone having a branch with `__`, right? That'd be one very ugly branch name and maybe they deserve an error code at that point.

> By the same token, removing one branch will remove the shared tag.
Wouldn't removing one branch result in the unintended behaviour of sustaining that shared tag because the one branch that wasn't deleted would trigger the filter?

**Comment by cowboyd** [comment]
> We don't have to worry about someone having a branch with __, right?

We should handle the case, it's easier than not handling it, and who knows maybe there will be some justification we don't know about?

The encoding for a branch with `_` would be `__` and a branch with `__` would be `____` and so on. It's not great, but the very fact that they are ugly is their own disincentive to use them.
