### ISSUE TITLE
Action still succeeds when comment fails to post

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/actions#17]
In this pull request workflow, the comment failed to post to GitHub. It looks like the comment token is misconfigured, but the workflow still succeeded 

https://github.com/microstates/microstates.js/commit/fe17889f91ba317930a070a9f7f0b7399a676917/checks?check_suite_id=260590046#step:8:23

**Comment by minkimcello** [comment]
Is this because Danger isn't returning the proper error code? I could try wrapping the execution of Danger CI in our code with a catch.

**Comment by cowboyd** [comment]
I'm not sure. It looks like it?

**Comment by minkimcello** [comment]
Not sure if I'm stating the obvious but I think this might have to do with Jack's token scope. This is the settings I had for my bot for the tests below:

![Screen Shot 2019-10-11 at 4 48 17 PM](https://user-images.githubusercontent.com/29791650/66686421-686b2500-ec4d-11e9-8957-6defff50b69a.png)
I've run this again to confirm it's not any github actions update causing the issue: [successful run](https://github.com/minkimcello/georgia/runs/257119945).

And an [unsuccessful run](https://github.com/minkimcello/georgia/commit/b5fb45dc6df7210fa5ee5df4b6ff609d4ccaef85/checks?check_suite_id=261883728) with invalid token to return an error.

And [similar issue](https://github.community/t5/How-to-use-Git-and-GitHub/Why-does-GitHub-API-require-admin-rights-to-leave-a-comment-on-a/td-p/357) of someone struggling to post comments on a public repo PR and they fixed it by making sure public_repo permission was set on the token.

**Comment by cowboyd** [comment]
Yeah, the issue isn’t that An insufficiently permissioned token fails, the issue is that an insufficiently permissioned token failed and the action succeeded

**Comment by minkimcello** [comment]
@cowboyd Should we close this?

**Comment by cowboyd** [comment]
Unless we've created a fix for it, then I don't think so.

**Comment by minkimcello** [comment]
The preview action has been refactored to node. If the comment fails to post through octokit, the yield should return an error now and therefore failing the workflow.

https://github.com/thefrontside/actions/blob/v2/publish-pr-preview/src/index.ts#L46

https://github.com/thefrontside/actions/blob/v2/publish-pr-preview/src/postGithubComment.ts#L32-L48

<blockquote><img src="https://opengraph.githubassets.com/9740490a1f7a45b56ac461b66bfd8c68469b705fd3e74fe2479d6e110a54d732/thefrontside/actions" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/thefrontside/actions">actions/index.ts at v2 · thefrontside/actions</a></strong></div><div>Collection of GitHub Actions created by Frontside. Contribute to thefrontside/actions development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/9740490a1f7a45b56ac461b66bfd8c68469b705fd3e74fe2479d6e110a54d732/thefrontside/actions" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/thefrontside/actions">actions/postGithubComment.ts at v2 · thefrontside/actions</a></strong></div><div>Collection of GitHub Actions created by Frontside. Contribute to thefrontside/actions development by creating an account on GitHub.</div></blockquote>
