### ISSUE TITLE
🐛 cannot publish a single-repo with sub-packages

### ISSUE THREAD

**Issue by jgnieuwhof** [thefrontside/actions#49]
We encountered an issue trying to publish [graphql-voyager](https://github.com/resideo/graphql-voyager) to the organization's package registry.

It's a single-repo (as opposed to a monorepo), however it contains an `example` directory which has a `package.json` file in it.

### Current Behaviour
The transparent publishing script assumes that this single-repo is a monorepo, due to the sub directory `package.json` files. Because of this it does not allow the root package to be published.

### Desired Behaviour
The script should give the option for the root package to be published, despite the presence of sub-packages.

In the GraphQL Voyager case this would allow publishing of the root package. The example packages could also be published by setting `private: false` in their `package.json`.

This would also give monorepo's the ability to publish their root package. This is not typically desired, however giving the option to do so does not seem to be particularly harmful.

**Comment by cowboyd** [comment]
If you ignore the examples directory does it then pick up the root?

**Comment by jgnieuwhof** [comment]
I did try ignoring the examples directory, but unfortunately the part of the script that ignores those packages is separate from the part of the script that checks for a monorepo (@minkimcello may have more details on that).

This issue may be something that magically disappears, or is far easier to tackle, after the bash -> JS rewrite.
