### ISSUE TITLE
Possible New Action: Auto-robotic Deprecation

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/actions#57]
## Context
From [this](https://github.com/thefrontside/bigtest/pull/238) pull request on [bigtest](github.com/thefrontside/bigtest), I was removing unused packages from the monorepo and the discussion of deprecating those packages was initiated.

But first to address some of the comments from that pull request:

@taras: `should we add a mechanism to release action to somehow deprecate packages?`
- Or we could create a separate action for it.

@cowboyd: `what about adding a deprecated flag to the package.json`
- Wouldn't this require us to keep the package we want to remove (or at least the package.json) on the repo for at least one cycle? tag deprecate flag and push => let action run to deprecate packages => remove package and push

## Solution
Create a new action to deprecate packages.

### Approach
- Rename `synchronize-with-npm` to `release` and create the new action as `deprecate`
- Have it run `on push` to `master` branch.
- The action would compile the name property of every package.json of its latest (presumably from a pull request merge) commit and the one prior.
- Compare the two list to see if any packages were removed and compile list of removed packages.
- Loop over the list and run `npm deprecate`.

**Comment by taras** [comment]
@minkimcello I think the workflow should be,
1. create a PR which adds deprecated: true flag to package.json
2. merge it to master, `release` action checks for deprecated: true flag and runs `npm deprecate`

**Comment by minkimcello** [comment]
@taras
Case #1:
1. Create a PR to deprecate package
2. Merge it to master to deprecate package
3. Create another PR to remove packages from repo
4. Merge to master

Case #2:
1. Create a PR to remove package
2. Merge to master
  - Release action does its thing
  - Deprecate action will find packages that have been removed and deprecate those packages

**Comment by taras** [comment]
I'm not a big fan of making separate actions. Ultimately, I want everything living in 1 utility... maybe we have different actions but I'm not sure yet.

@cowboyd what do you think?

**Comment by minkimcello** [comment]
Resolved with #58, #59, and #60.
